"""fifth migration

Revision ID: 223daad11191
Revises: f8bcbad43ad5
Create Date: 2020-12-13 13:01:53.286259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '223daad11191'
down_revision = 'f8bcbad43ad5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blog', 'description',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('blog', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_blog_description'), 'blog', ['description'], unique=False)
    op.create_index(op.f('ix_blog_title'), 'blog', ['title'], unique=False)
    op.drop_constraint('blog_description_fkey', 'blog', type_='foreignkey')
    op.drop_index('ix_users_username', table_name='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.create_foreign_key('blog_description_fkey', 'blog', 'users', ['description'], ['id'])
    op.drop_index(op.f('ix_blog_title'), table_name='blog')
    op.drop_index(op.f('ix_blog_description'), table_name='blog')
    op.alter_column('blog', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('blog', 'description',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
