"""fourth migration

Revision ID: f8bcbad43ad5
Revises: 2c1e963a86f2
Create Date: 2020-12-13 09:21:15.037756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8bcbad43ad5'
down_revision = '2c1e963a86f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pic_path', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('blog_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['blog_id'], ['blog.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('blog', sa.Column('description', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'blog', 'users', ['description'], ['id'])
    op.drop_column('blog', 'blog')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('blog', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'blog', type_='foreignkey')
    op.drop_column('blog', 'description')
    op.drop_table('comments')
    op.drop_table('profile_photos')
    op.drop_table('subscribers')
    # ### end Alembic commands ###
